version: "3.8"
   
services:
  web:
    build: ./app
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8080:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
    ports:
      - 5435:5432

volumes:
  postgres_data:
