# Generated by Django 3.1.2 on 2021-09-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cnab',
            new_name='Movimentacao',
        ),
    ]
