# Generated by Django 3.1.2 on 2021-09-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0002_auto_20210923_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='hora',
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateTimeField(verbose_name='Data da ocorrência'),
        ),
    ]
