# Generated by Django 3.1.2 on 2021-09-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0003_auto_20210923_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='cartao',
            field=models.CharField(max_length=12, verbose_name='Cartão'),
        ),
    ]
