# Generated by Django 3.1.2 on 2021-09-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0004_auto_20210923_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('1', 'Débito'), ('2', 'Boleto'), ('3', 'Financiamento'), ('4', 'Crédito'), ('5', 'Recebimento Empréstimo'), ('6', 'Vendas'), ('8', 'Recebimento TED'), ('7', 'Recebimento'), ('9', 'Aluguel')], max_length=1, verbose_name='Tipo de Transação'),
        ),
    ]
